"""Initial schema and Shabbat Lock

Revision ID: d8e5270ca9c5
Revises: 
Create Date: 2026-04-17 14:36:59.075740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e5270ca9c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('actorId', sa.BigInteger(), nullable=False),
    sa.Column('targetId', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('msgLink', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actionlog'))
    )
    with op.batch_alter_table('actionlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actionlog_chatId'), ['chatId'], unique=False)
        batch_op.create_index(batch_op.f('ix_actionlog_targetId'), ['targetId'], unique=False)

    op.create_table('allowedchannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('channelId', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allowedchannel'))
    )
    with op.batch_alter_table('allowedchannel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowedchannel_chatId'), ['chatId'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('grantedBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_chatId'), ['chatId'], unique=False)

    op.create_table('channelprotect',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('antiChannel', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('antiAnon', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_channelprotect'))
    )
    op.create_table('chatrules',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('privateMode', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_chatrules'))
    )
    op.create_table('chatsettings',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('chatType', sa.String(length=50), server_default=sa.text("'supergroup'"), nullable=False),
    sa.Column('floodThreshold', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('floodWindow', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('floodAction', sa.String(length=50), server_default=sa.text("'mute'"), nullable=False),
    sa.Column('raidEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('raidThreshold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('raidWindow', sa.Integer(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('raidTime', sa.String(length=20), server_default=sa.text("'6h'"), nullable=False),
    sa.Column('raidActionTime', sa.String(length=20), server_default=sa.text("'1h'"), nullable=False),
    sa.Column('raidAction', sa.String(length=50), server_default=sa.text("'lock'"), nullable=False),
    sa.Column('warnLimit', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('warnAction', sa.String(length=50), server_default=sa.text("'kick'"), nullable=False),
    sa.Column('warnExpiry', sa.String(length=50), server_default=sa.text("'never'"), nullable=False),
    sa.Column('captchaEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('captchaMode', sa.String(length=50), server_default=sa.text("'button'"), nullable=False),
    sa.Column('captchaTimeout', sa.Integer(), server_default=sa.text('(120)'), nullable=False),
    sa.Column('logChannelId', sa.BigInteger(), nullable=True),
    sa.Column('logChannelName', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('welcomeEnabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('welcomeText', sa.Text(), nullable=True),
    sa.Column('goodbyeEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('goodbyeText', sa.Text(), nullable=True),
    sa.Column('cleanJoin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanLeave', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanPinned', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanAllServices', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanServiceTypes', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('blacklistAction', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('stickerAction', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('langBlockAction', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('urlScannerEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('gsbKey', sa.Text(), nullable=True),
    sa.Column('urlScannerAction', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('blacklistScanButtons', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('botPrivileges', sa.Text(), nullable=True),
    sa.Column('reactionsEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('reactions', sa.Text(), server_default=sa.text("'👍'"), nullable=False),
    sa.Column('reactionMode', sa.Text(), server_default=sa.text("'all'"), nullable=False),
    sa.Column('watermarkEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('watermarkText', sa.Text(), nullable=True),
    sa.Column('signatureEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('signatureText', sa.Text(), nullable=True),
    sa.Column('buttons', sa.Text(), nullable=True),
    sa.Column('signaturePosition', sa.String(length=10), server_default=sa.text("'below'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chatsettings'))
    )
    op.create_table('disabledcommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disabledcommand'))
    )
    with op.batch_alter_table('disabledcommand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disabledcommand_chatId'), ['chatId'], unique=False)

    op.create_table('federation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ownerId', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_federation'))
    )
    op.create_table('globalban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('bannedBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_globalban')),
    sa.UniqueConstraint('userId', name=op.f('uq_globalban_userId'))
    )
    op.create_table('reportsetting',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_reportsetting'))
    )
    op.create_table('scheduledmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sendAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cronExpr', sa.String(length=100), nullable=True),
    sa.Column('jobId', sa.String(length=100), nullable=False),
    sa.Column('createdBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduledmessage')),
    sa.UniqueConstraint('jobId', name=op.f('uq_scheduledmessage_jobId'))
    )
    with op.batch_alter_table('scheduledmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduledmessage_chatId'), ['chatId'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduledmessage_sendAt'), ['sendAt'], unique=False)

    op.create_table('slowmodesetting',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('interval', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_slowmodesetting'))
    )
    op.create_table('sudouser',
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('addedBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_sudouser'))
    )
    op.create_table('timedaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timedaction'))
    )
    with op.batch_alter_table('timedaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timedaction_expiresAt'), ['expiresAt'], unique=False)

    op.create_table('userconnection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('activeChatId', sa.BigInteger(), nullable=True),
    sa.Column('chatType', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userconnection')),
    sa.UniqueConstraint('userId', name=op.f('uq_userconnection_userId'))
    )
    op.create_table('usersettings',
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_usersettings'))
    )
    op.create_table('aichatcontext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('messageId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('userName', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_aichatcontext_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aichatcontext'))
    )
    with op.batch_alter_table('aichatcontext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aichatcontext_chatId'), ['chatId'], unique=False)

    op.create_table('aiguardsettings',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('isTextEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('apiKey', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('isImageEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_aiguardsettings_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_aiguardsettings'))
    )
    op.create_table('aisettings',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), server_default=sa.text("'openai'"), nullable=False),
    sa.Column('apiKey', sa.Text(), nullable=True),
    sa.Column('modelId', sa.String(length=100), nullable=True),
    sa.Column('systemPrompt', sa.Text(), nullable=True),
    sa.Column('customInstruction', sa.Text(), nullable=True),
    sa.Column('isAssistantEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_aisettings_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_aisettings'))
    )
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('isRegex', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('isWildcard', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('action', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_blacklist_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklist'))
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_chatId'), ['chatId'], unique=False)

    op.create_table('blockedentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('entityType', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), server_default=sa.text("'delete'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_blockedentity_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockedentity'))
    )
    with op.batch_alter_table('blockedentity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockedentity_chatId'), ['chatId'], unique=False)

    op.create_table('blockedlanguage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('langCode', sa.String(length=10), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_blockedlanguage_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockedlanguage'))
    )
    with op.batch_alter_table('blockedlanguage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockedlanguage_chatId'), ['chatId'], unique=False)

    op.create_table('chatadmins',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('privileges', sa.Text(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_chatadmins_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', 'userId', name=op.f('pk_chatadmins'))
    )
    op.create_table('chatcleaner',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('cleanDeleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanFake', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanInactiveDays', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cleanerRunTime', sa.String(length=5), server_default=sa.text("'04:00'"), nullable=False),
    sa.Column('cleanerTimeChangedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastRunDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_chatcleaner_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_chatcleaner'))
    )
    op.create_table('chatnightlock',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('isEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('startTime', sa.String(length=5), server_default=sa.text("'23:00'"), nullable=False),
    sa.Column('endTime', sa.String(length=5), server_default=sa.text("'07:00'"), nullable=False),
    sa.Column('lastPermissions', sa.Text(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_chatnightlock_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_chatnightlock'))
    )
    op.create_table('chatshabbatlock',
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('isEnabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('lastPermissions', sa.Text(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_chatshabbatlock_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('chatId', name=op.f('pk_chatshabbatlock'))
    )
    op.create_table('fedadmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fedId', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fedId'], ['federation.id'], name=op.f('fk_fedadmin_fedId_federation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fedadmin'))
    )
    op.create_table('fedban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fedId', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('bannedBy', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fedId'], ['federation.id'], name=op.f('fk_fedban_fedId_federation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fedban'))
    )
    op.create_table('fedchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fedId', sa.String(length=36), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fedId'], ['federation.id'], name=op.f('fk_fedchat_fedId_federation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fedchat')),
    sa.UniqueConstraint('chatId', name=op.f('uq_fedchat_chatId'))
    )
    op.create_table('fedsubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriberId', sa.String(length=36), nullable=False),
    sa.Column('publisherId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['publisherId'], ['federation.id'], name=op.f('fk_fedsubscription_publisherId_federation')),
    sa.ForeignKeyConstraint(['subscriberId'], ['federation.id'], name=op.f('fk_fedsubscription_subscriberId_federation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fedsubscription'))
    )
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('responseType', sa.String(length=50), server_default=sa.text("'text'"), nullable=False),
    sa.Column('fileId', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_filter_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filter'))
    )
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filter_chatId'), ['chatId'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('isPrivate', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_note_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_chatId'), ['chatId'], unique=False)

    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('messageType', sa.String(length=50), server_default=sa.text("'text'"), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('fileId', sa.String(length=255), nullable=True),
    sa.Column('additionalData', sa.Text(), nullable=True),
    sa.Column('sendTime', sa.String(length=5), server_default=sa.text("'12:00'"), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_reminder_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder'))
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_chatId'), ['chatId'], unique=False)

    op.create_table('stickerblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('setName', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_stickerblock_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stickerblock'))
    )
    with op.batch_alter_table('stickerblock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stickerblock_chatId'), ['chatId'], unique=False)
        batch_op.create_index(batch_op.f('ix_stickerblock_setName'), ['setName'], unique=False)

    op.create_table('userwarn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actorId', sa.BigInteger(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chatId'], ['chatsettings.id'], name=op.f('fk_userwarn_chatId_chatsettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userwarn'))
    )
    with op.batch_alter_table('userwarn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userwarn_chatId'), ['chatId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userwarn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userwarn_chatId'))

    op.drop_table('userwarn')
    with op.batch_alter_table('stickerblock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stickerblock_setName'))
        batch_op.drop_index(batch_op.f('ix_stickerblock_chatId'))

    op.drop_table('stickerblock')
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_chatId'))

    op.drop_table('reminder')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_chatId'))

    op.drop_table('note')
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filter_chatId'))

    op.drop_table('filter')
    op.drop_table('fedsubscription')
    op.drop_table('fedchat')
    op.drop_table('fedban')
    op.drop_table('fedadmin')
    op.drop_table('chatshabbatlock')
    op.drop_table('chatnightlock')
    op.drop_table('chatcleaner')
    op.drop_table('chatadmins')
    with op.batch_alter_table('blockedlanguage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockedlanguage_chatId'))

    op.drop_table('blockedlanguage')
    with op.batch_alter_table('blockedentity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockedentity_chatId'))

    op.drop_table('blockedentity')
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_chatId'))

    op.drop_table('blacklist')
    op.drop_table('aisettings')
    op.drop_table('aiguardsettings')
    with op.batch_alter_table('aichatcontext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aichatcontext_chatId'))

    op.drop_table('aichatcontext')
    op.drop_table('usersettings')
    op.drop_table('userconnection')
    with op.batch_alter_table('timedaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timedaction_expiresAt'))

    op.drop_table('timedaction')
    op.drop_table('sudouser')
    op.drop_table('slowmodesetting')
    with op.batch_alter_table('scheduledmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduledmessage_sendAt'))
        batch_op.drop_index(batch_op.f('ix_scheduledmessage_chatId'))

    op.drop_table('scheduledmessage')
    op.drop_table('reportsetting')
    op.drop_table('globalban')
    op.drop_table('federation')
    with op.batch_alter_table('disabledcommand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disabledcommand_chatId'))

    op.drop_table('disabledcommand')
    op.drop_table('chatsettings')
    op.drop_table('chatrules')
    op.drop_table('channelprotect')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_chatId'))

    op.drop_table('approval')
    with op.batch_alter_table('allowedchannel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowedchannel_chatId'))

    op.drop_table('allowedchannel')
    with op.batch_alter_table('actionlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actionlog_targetId'))
        batch_op.drop_index(batch_op.f('ix_actionlog_chatId'))

    op.drop_table('actionlog')
    # ### end Alembic commands ###
